---
- hosts: all

  tasks:
    - name: Ensure the directory exists
      ansible.builtin.file:
        path: ~/awx-on-k3s/playlists/resolv.conf
        state: directory
        mode: '0755'
    - name: deployment based on operator 2.18/awx24.5.0
      copy:
        dest: ~/awx-on-k3s/playlists/resolv.conf/awx-web-deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            labels:
              app.kubernetes.io/component: awx
              app.kubernetes.io/managed-by: awx-operator
              app.kubernetes.io/name: awx-web
              app.kubernetes.io/operator-version: 2.18.0
              app.kubernetes.io/part-of: awx
              app.kubernetes.io/version: 24.5.0
            name: awx-web
            namespace: awx
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/component: awx
                app.kubernetes.io/managed-by: awx-operator
                app.kubernetes.io/name: awx-web
            strategy:
              rollingUpdate:
                maxSurge: 25%
                maxUnavailable: 25%
              type: RollingUpdate
            template:
              metadata:
                labels:
                  app.kubernetes.io/component: awx
                  app.kubernetes.io/managed-by: awx-operator
                  app.kubernetes.io/name: awx-web
                  app.kubernetes.io/operator-version: 2.18.0
                  app.kubernetes.io/part-of: awx
                  app.kubernetes.io/version: 24.5.0
              spec:
                containers:
                - args:
                  - redis-server
                  - /etc/redis.conf
                  image: docker.io/redis:7
                  imagePullPolicy: IfNotPresent
                  name: redis
                  volumeMounts:
                  - mountPath: /etc/redis.conf
                    name: awx-redis-config
                    readOnly: true
                    subPath: redis.conf
                  - mountPath: /var/run/redis
                    name: awx-redis-socket
                  - mountPath: /data
                    name: awx-redis-data
                - args:
                  - /usr/bin/launch_awx_web.sh
                  env:
                  - name: AWX_COMPONENT
                    value: web
                  - name: SUPERVISOR_CONFIG_PATH
                    value: /etc/supervisord_web.conf
                  - name: MY_POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: MY_POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: UWSGI_MOUNT_PATH
                    value: /
                  image: quay.io/ansible/awx:24.5.0
                  imagePullPolicy: IfNotPresent
                  name: awx-web
                  ports:
                  - containerPort: 8052
                    protocol: TCP
                  volumeMounts:
                  - mountPath: /etc/tower/uwsgi.ini
                    name: awx-uwsgi-config
                    readOnly: true
                    subPath: uwsgi.conf
                  - mountPath: /etc/tower/conf.d/execution_environments.py
                    name: awx-application-credentials
                    readOnly: true
                    subPath: execution_environments.py
                  - mountPath: /etc/tower/conf.d/credentials.py
                    name: awx-application-credentials
                    readOnly: true
                    subPath: credentials.py
                  - mountPath: /etc/tower/conf.d/ldap.py
                    name: awx-application-credentials
                    readOnly: true
                    subPath: ldap.py
                  - mountPath: /etc/tower/SECRET_KEY
                    name: awx-secret-key
                    readOnly: true
                    subPath: SECRET_KEY
                  - mountPath: /etc/tower/settings.py
                    name: awx-settings
                    readOnly: true
                    subPath: settings.py
                  - mountPath: /etc/nginx/nginx.conf
                    name: awx-nginx-conf
                    readOnly: true
                    subPath: nginx.conf
                  - mountPath: /var/run/redis
                    name: awx-redis-socket
                  - mountPath: /var/run/awx-rsyslog
                    name: rsyslog-socket
                  - mountPath: /var/lib/awx/projects
                    name: awx-projects
                  - mountPath: /etc/receptor/tls/ca/mesh-CA.crt
                    name: awx-receptor-ca
                    readOnly: true
                    subPath: tls.crt
                  - mountPath: /etc/receptor/tls/ca/mesh-CA.key
                    name: awx-receptor-ca
                    readOnly: true
                    subPath: tls.key
                  - mountPath: /etc/receptor/work_public_key.pem
                    name: awx-receptor-work-signing
                    readOnly: true
                    subPath: work-public-key.pem
                  - mountPath: /etc/resolv.conf
                    name: resolv-conf
                    subPath: resolv.conf
                - args:
                  - /usr/bin/launch_awx_rsyslog.sh
                  env:
                  - name: SUPERVISOR_CONFIG_PATH
                    value: /etc/supervisord_rsyslog.conf
                  image: quay.io/ansible/awx:24.5.0
                  imagePullPolicy: IfNotPresent
                  name: awx-rsyslog
                  volumeMounts:
                  - mountPath: /etc/tower/conf.d/credentials.py
                    name: awx-application-credentials
                    readOnly: true
                    subPath: credentials.py
                  - mountPath: /etc/tower/SECRET_KEY
                    name: awx-secret-key
                    readOnly: true
                    subPath: SECRET_KEY
                  - mountPath: /etc/tower/settings.py
                    name: awx-settings
                    readOnly: true
                    subPath: settings.py
                  - mountPath: /var/run/redis
                    name: awx-redis-socket
                  - mountPath: /var/run/awx-rsyslog
                    name: rsyslog-socket
                initContainers:
                - command:
                  - /bin/sh
                  - -c
                  - ""
                  image: quay.io/ansible/awx-ee:24.5.0
                  imagePullPolicy: IfNotPresent
                  name: init
                - command:
                  - /bin/sh
                  - -c
                  - "echo 'search $(grep search /etc/resolv.conf | awk \"{print $0, 'anti.net'}\")' > /etc/resolv.conf"
                  image: busybox
                  name: init-update-resolv-conf
                  volumeMounts:
                    - name: resolv-conf
                      mountPath: /etc/resolv.conf
                - command:
                  - /bin/sh
                  - -c
                  - |
                    chmod 775 /var/lib/awx/projects
                    chgrp 1000 /var/lib/awx/projects
                  env:
                  - name: MY_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  image: quay.io/centos/centos:stream9
                  imagePullPolicy: IfNotPresent
                  name: init-projects
                  volumeMounts:
                  - mountPath: /var/lib/awx/projects
                    name: awx-projects
                serviceAccountName: awx
                volumes:
                - name: awx-receptor-ca
                  secret:
                    secretName: awx-receptor-ca
                - name: awx-receptor-work-signing
                  secret:
                    secretName: awx-receptor-work-signing
                - name: awx-application-credentials
                  secret:
                    items:
                    - key: credentials.py
                      path: credentials.py
                    - key: ldap.py
                      path: ldap.py
                    - key: execution_environments.py
                      path: execution_environments.py
                    secretName: awx-app-credentials
                - name: awx-secret-key
                  secret:
                    items:
                    - key: secret_key
                      path: SECRET_KEY
                    secretName: awx-secret-key
                - configMap:
                    items:
                    - key: settings
                      path: settings.py
                    name: awx-awx-configmap
                  name: awx-settings
                - configMap:
                    items:
                    - key: nginx_conf
                      path: nginx.conf
                    name: awx-awx-configmap
                  name: awx-nginx-conf
                - configMap:
                    items:
                    - key: redis_conf
                      path: redis.conf
                    name: awx-awx-configmap
                  name: awx-redis-config
                - configMap:
                    items:
                    - key: uwsgi_conf
                      path: uwsgi.conf
                    name: awx-awx-configmap
                  name: awx-uwsgi-config
                - emptyDir: {}
                  name: awx-redis-socket
                - emptyDir: {}
                  name: resolv-conf
                - emptyDir: {}
                  name: awx-redis-data
                - emptyDir: {}
                  name: rsyslog-socket
                - emptyDir: {}
                  name: receptor-socket
                - configMap:
                    items:
                    - key: receptor_conf
                      path: receptor.conf
                    name: awx-awx-configmap
                  name: awx-receptor-config
                - name: awx-projects
                  persistentVolumeClaim:
                    claimName: awx-projects-claim

    - name: Apply new deployment
      shell: kubectl -n awx apply -f ~/awx-on-k3s/playlists/resolv.conf/awx-web-deployment.yaml

    - name: Rollout restart and monitor until done
      shell: kubectl -n awx rollout restart deployment awx-web
